const COMMANDS: &[&str] = &["connect", "send", "close"];

fn main() {
    // Autogenerates one `allow-<cmd>` / `deny-<cmd>` permission per
    // command under `permissions/autogenerated/`; the hand-written
    // `permissions/default.toml` bundles them as `peerline-iroh:default`.
    tauri_plugin::Builder::new(COMMANDS).build();
}
